"""
Django settings for medicine_shop_project project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import dotenv_values

dotenv_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env')

config = dotenv_values(dotenv_path)

CART_SESSION_ID = 'cart'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'fontawesomefree',
    'django_filters',
    'debug_toolbar',
    'captcha',
    'staff_side.apps.StaffSideConfig',
    'client_side.apps.ClientSideConfig',
    'accounts.apps.AccountsConfig',
    'cart.apps.CartConfig',

    'allauth',  # само приложение авторизации
    'allauth.account',  # модель и её формы для аккаунтов
    'allauth.socialaccount',  # модель и её формы для аккаунтов в соц сетях
    'allauth.socialaccount.providers.yandex',  # подключение яндекс сервисов авторизации
    'allauth.socialaccount.providers.vk',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'medicine_shop_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # обрабатывает шаблоны в нашем приложении
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'medicine_shop_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

INTERNAL_IPS = [
    '127.0.0.1',
]

# STATIC_URL – префикс URL-адреса для статических файлов;
STATIC_URL = 'static/'
# STATICFILES_DIRS – список дополнительных (нестандартных) путей к
# статическим файлам, используемых для сбора и для режима отладки.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "client_side/static"),
    os.path.join(BASE_DIR, "staff_side/static"),
]
# STATIC_ROOT – путь к общей статической папке,
# используемой реальным веб-сервером;
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CAPTCHA_FONT_SIZE = 26
CAPTCHA_FOREGROUND_COLOR = 'red'
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'

# LOGIN_REDIRECT_URL = '/'

# это тонкие настройки шаблонов авторизации и регистрации
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
#
EMAIL_CONFIRMATION_SIGNUP = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1

# Рассположено в текущем каталоге проекта. BASE_DIR- определяет текущую папку
# нашего проекта. К рабочей папке добавляется подкаталог media.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# доб в Url графическим файлам префикс media.
MEDIA_URL = '/media/'






# EMAIL_HOST = 'smtp.mail.ru'
# EMAIL_PORT = 465  # порт smtp сервера тоже одинаковый
# EMAIL_HOST_USER = ''  # ваше имя пользователя, например если ваша почта user@yandex.ru,
# # то сюда надо писать user, иными словами, это всё то что идёт до собаки
# EMAIL_HOST_PASSWORD = config['EMAIL_HOST_PASSWORD']  # пароль от почты
# EMAIL_USE_SSL = True
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER + '@mail.ru'

# Экспортируем модель базы данных:
# manage.py dumpdata --indent 2 > mydata.json
# Экспортируем всю базы данных:
# исключить таблицы contenttypes и auth.permissions:
# manage.py dumpdata --exclude auth.permission --exclude contenttypes --indent 2 > db.json
# python manage.py loaddata mydata.json # востанавливает удалённую БД
# python manage.py  flush #  удаляет БД