# Generated by Django 4.1.4 on 2022-12-30 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_country', models.CharField(max_length=250, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('legacy_name', models.CharField(max_length=250, unique=True, verbose_name='Название организации')),
                ('legacy_address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('contacts', models.CharField(max_length=250, verbose_name='Контакты')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('trade_name', models.CharField(max_length=250, unique=True, verbose_name='Наименование')),
                ('international_name', models.CharField(max_length=250, unique=True, verbose_name='Международное название')),
                ('structure', models.TextField(default='Состав лекарства', verbose_name='Состав')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('slug', models.SlugField(default='', unique=True)),
                ('_price_increment', models.IntegerField(verbose_name='Наценка')),
                ('with_recipe', models.BooleanField(choices=[(True, 'по рецепту'), (False, 'без рецепта')], default=False, verbose_name='По рецепту')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('_amount', models.IntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('receive_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('delivery_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи заказа')),
                ('cost', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('complete', models.BooleanField(default=False, verbose_name='Готовность заказа')),
                ('medicines', models.ManyToManyField(through='client_side.MedicineOrder', to='client_side.medicine', verbose_name='Лекарства')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.order'),
        ),
        migrations.CreateModel(
            name='MedicineManufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.manufacturer', verbose_name='Производитель')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.medicine', verbose_name='Название лекарства')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.ManyToManyField(through='client_side.MedicineManufacturer', to='client_side.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('trade_name', 'international_name')},
        ),
    ]
