# Generated by Django 4.1.4 on 2023-01-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='amount_on_stock',
            field=models.IntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterUniqueTogether(
            name='medicineorder',
            unique_together={('medicine', 'order')},
        ),
    ]
