# Generated by Django 4.1.4 on 2023-01-11 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0002_medicine_amount_on_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='_price_increment',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Негодно к продаже!')], verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='with_recipe',
            field=models.BooleanField(choices=[(True, 'по рецепту'), (False, 'без рецепта')], default=False, verbose_name='Условия отпуска'),
        ),
    ]
