# Generated by Django 4.1.4 on 2023-01-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0004_cart_medicinecart_cart_medicines_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Стоимость'),
        ),
    ]
