# Generated by Django 4.1.4 on 2022-12-29 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backgrounds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('educational_institution', models.CharField(max_length=250, verbose_name='Учебное заведение')),
                ('education_completeness', models.CharField(choices=[('FULL', 'Полное'), ('NOT_FULL', 'Неполное')], default='FULL', max_length=50, verbose_name='Полнота образования')),
            ],
            options={
                'verbose_name': 'Уч. заведение',
                'verbose_name_plural': 'Уч. заведения',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('post_name', models.CharField(max_length=250, verbose_name='Должность')),
                ('responsibility', models.CharField(max_length=1000, verbose_name='Обязанности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sex', models.CharField(choices=[('M', 'Муж'), ('W', 'Жен')], default='M', max_length=1, verbose_name='Пол')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Дата рождения')),
                ('schedule_type', models.CharField(choices=[('FLEXIBLE', 'Гибкий график'), ('FULL_TIME', 'Полный день'), ('PART_TIME', 'Частичная занятость')], default='FULL_TIME', max_length=250, verbose_name='Расписание')),
                ('_salary', models.FloatField(default=0.0, verbose_name='ЗП, $')),
                ('vacations', models.IntegerField(default=25, verbose_name='Дней отпуска')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff_side.backgrounds', verbose_name='Образование')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff_side.positions', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['second_name'],
            },
        ),
    ]
