# Generated by Django 4.1.2 on 2022-12-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('schedule_type', models.CharField(choices=[('FLEXIBLE', 'Flexible'), ('FULL_TIME', 'Full time')], default='FULL_TIME', max_length=250)),
                ('background', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('_salary', models.FloatField(default=0.0)),
                ('vacations', models.IntegerField(default=25)),
            ],
        ),
    ]
