# Generated by Django 4.1.4 on 2022-12-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_side', '0004_alter_backgrounds_options_alter_positions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgrounds',
            name='full_education',
        ),
        migrations.AddField(
            model_name='backgrounds',
            name='education_completeness',
            field=models.CharField(choices=[('FULL', 'Полное'), ('NOT_FULL', 'Неполное')], default='FULL', max_length=50, verbose_name='Полнота образования'),
        ),
    ]
