# Generated by Django 4.1.4 on 2022-12-27 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_side', '0006_alter_backgrounds_education_completeness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='education_completeness',
            field=models.CharField(choices=[('FULL', 'Полное'), ('NOT_FULL', 'Неполное')], default='FULL', max_length=50, verbose_name='Полнота образования'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='schedule_type',
            field=models.CharField(choices=[('FLEXIBLE', 'Гибкий график'), ('FULL_TIME', 'Полный день'), ('PART_TIME', 'Частичная занятость')], default='FULL_TIME', max_length=250, verbose_name='Расписание'),
        ),
    ]
